---
title: "Albums (and other tunes)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
----


### Lizzy McAlpine - Older (and Wiser) - 2024  
<br>
**6 October 2024**

<br>
**Naomi**

I started listening to this on Sunday afternoon, after our call. I couldn't have asked for a more fitting first track. That filled me with joy. 
<br>
But the rest of the album doesn't feel very notable to me; just a larger, longer iteration of her previous work. Soft, wistful, and a little melancholic. In my opinion, there's nothing particularly innovative or genius about it. It is not unpleasant! But it is not extraordinary. 
<br>
Songs I like include "All Falls Down" and "Method Acting" (I tend to have a soft spot for demos). Not for lyrics necessarily, just for vibes. 
<br>
Will I have this album on loop? Definitely not. Maybe I'll pull a song out every now and then for a sad playlist, who knows. 
<br>
**OVERALL: 3/5 STARS** 

<br>

**Axel**

During the last week I've been listening to the album, both as background music while doing things and actively listening to the instruments and the lyrics. This was two very different experiences for me.
<br>
Playing this while at work, studying or anything else when my focus isn't primarily on the music, everything blends together to one long Lizzy McAlpine sad song with no real distinctions. Listening to a sad Lizzy McAlpine song isn't a bad experience, I like her music but it gets repetitive when  song is one hour and five minutes. My conclusion is that most of the instrumentals to the songs isn't very engaging.
<br>
Sitting down with something to drink and just listening to the lyrics gave me another experience. I realised it's a album about a bad relationship, who would've thought?? Not this guy! The story might not be the most innovative but the album has a narrative and I liked that because every new song further explains things about the relationship. The story being told is about the life cycle of a dysfunctional couple where the narrator (Lizzy?) wants appreciation while their partner wants someone to love, no one wants to "pull the plug" even though both are unhappy. It is relatable but also a bit frustrating, you can only sing about these problem so many times, just break up already?? I guess it represent the struggle well but it doesn't make it an interesting story.
<br>
Listening to some songs with the narrative in mind does something though, for example "Come Down Soon", it's about being in the honeymoon phase of the relationship and anticipating the happiness you feel to fade with time as the relationship progress. My feeling is that the song is a cry for relationship that doesn't end this way and maybe, just maybe, that the current relationship might prove to be different. The rest of the album does however cement the fact the this also fails to meet any expectations. Lizzy sings "oh it'll come down soon, nothing this good ever lasts this long for me" and the rest of the albums proves that. On top of this Lizzy sings about falling into old patterns and never learning from her mistakes. The album is called Older (and Wiser) but I think she could've left out the parentheses. This would however not work as she already have a album with this name, maybe "the definition of insanity"? 
<br>
I do like the album, it just isn't very unique. You've already heard the songs even though you haven't. I think it lacks the instrumental diversity or enough engaging lyrics to be a good album to either 1) listen to while doing other tasks or 2) to just listen to. My favorite songs are "All Falls Down", "Method Acting" and "Pushing It Down and Praying" (I'm not copying you Naomi! I guess we just have the same taste).
<br>
**OVERALL: 3/5 STARS** 
<br>
P.S. I don't think the album should be called "the definition of insanity", that's a bit harsh, but she doesn't seem to have become any wiser


----


### Charli xcx and Bon Iver - I think about it all the time featuring bon iver - 2024  
<br>
**11 October 2024**

<br>
**Naomi**  

I really like hyperpop in theory. It is an unarguably gay genre, dominated by queer artists and consumed en masse by queer people. To me, that has something to do with the subversive appeal of taking a culturally "feminine" thing -- in this case, the bubbly, women-dominated pop sound -- and exaggerating it to the extreme to make something dramatic, unapologetic, and almost grating. It's appealing because it plays with expectations by being simultaneously derived from musical norms and still uniquely counter to them. It's pop music in drag. 
<br>
Charli xcx is at the forefront of hyperpop, and obviously an icon for the gays, so I feel the need to give her songs a chance on those grounds alone. I can concede that she has released some incredible beats for drunk nights on the dance floor (Hot In It was an invaluable part of my gay London party era), but honestly, I don't like the majority of her stuff.
<br>
Regarding this particular single: songs that are basically just someone talking over a set of synthetic noises sometimes work for me (see: BROCKHAMPTON) but not this time. The verses don't feel rhythmic or musical at all. The chorus and Bon Iver's contributions are the only salvageable parts, but they're not doing enough to carry the song.
<br>
I must also say that I can hear Kendall's voice in my head whenever I listen to anything Charli, and I know that she would argue that the lyrics to this one are deep . . . but I'm not sure I agree with her. And the line about walking through Stockholm didn't make it into this version, so I can't even give the song points for that.
<br>
The world agreed this was a brat summer, but let's leave it there. I can't support a brat fall.
<br>
**OVERALL: 2/5 STARS**

<br>

**Axel**

i’m always up for a unexpected collab, as long as it is good or is at least so crazy that it’s interesting. for example, the collab Charli did with Robyn and Yung Lean for 360, unexpected (referring to Yung Lean) and very different from the original - perfect! but Charli's and Bon Ivers version of “i think about it all the time” has nothing in that regard unfortunately. this was just too plain and also too similar to the original. i’m also starting to feel a very small, super duper small, you can’t imagine how small, Charli fatigue.i get it she’s really cool and all but chill out a bit.
<br>
i also think that the song doesn’t work good as a single. Kendall pointed out during her visit in sweden that Charli decided to put “itaiatt”, a song about not knowing whether she wants become a mother or not, just before 365, a song about popping pills at the club. In that context the song is good, but on its own it lacks the nuances and comedic touch.
<br>
the best part of the single is the cover, it’s still fun to put black text on a lime green background, fight me.
<br>
**OVERALL: 1.5/5 STARS** 


----


### Ms. Lauryn Hill - The Miseducation of Lauryn Hill - 1998 
<br>
**13 October 2024**

<br>
**Naomi**  

Listening to this after last week's "Older (and Wiser)" was honestly a jarring contrast. The difference in musical quality -- whether you consider lyrics, instrumentals, innovation, cohesion, or general artistry -- is staggering.
<br>
But no need to tear into Lizzy McAlpine to appreciate this. There's obviously a reason why it was named one of the top ten best albums of all time by the Rolling Stones. The songs are catchy but still rich and complex, diverse in tone and style but still masterfully tied together into an album, and the vocals!!! The vocals are unbelievable.
<br>
Honestly, I feel like I don't have the musical knowledge or vocabulary to write a review that would do this album justice. What I will say is that I think it gets at what it means to be human -- to grapple with the power dynamics that structure your life, to reflect on the romances that shaped you, and to be moved by the wonderful things you can feel for other people. To assert yourself, to lose yourself, and to find yourself again in love. It's brilliant. I'll leave it there.
<br>
As a last note: my favorite song, which was a pretty easy pick for me, is Tell Him. I know that it has religious undertones, and those aren't really relevant to me, but I didn't quite catch those on my first listen and after that it was too late. Most importantly, it has my favorite line of the album:
<br>
"If I lack love, then I am nothing at all."
<br>
**OVERALL: 5/5 STARS**

<br>

**Axel**

listening to “The Miseducation of Lauryn Hill” has been a breath of fresh air, it’s happy and upbeat without being too superficial or uninteresting. i would describe the experience like this: last week was dark and gloomy, accompanied by Lizzy McAlpine, this week was colourful and cozy.
<br>
my overall experience of the album was positive, both from a instrumental and lyrical point of view. you follow Lauryn Hill through topics related to love and relationships like break ups, having a child at a young age, and falling in love, together with a groovy beat that fails to disappoint. i had a hard time not comparing it to “Older (and wiser)”, as the album is fresh in memory, the lyrics' themes sometimes overlap and made me realise why i like Hill's lyrics so much. Lauryn Hill knows her own self worth and won’t let anyone change that, for example in “Lost Ones” in the chorus, she says this to an ex regarding their break up “you might win some, but you just lost one” - hell yeah they did! another thing i really liked was the versatility of this album, you can study, cook, exercise, basically everything to this album. it’s not too intense, not too slow, it’s perfect!
<br>
the only negative thing i have to say is that the album lacks is the “perfect song”, the song that hits you like a train and that you put on repeat until you hate it, then forget it, then rediscover it, then hate it again, then rediscover it,  until forever. the songs are good, really good but doesn’t reach that standard.
<br>
my favourite song is “I Used to Love Him”, i think it contains the best parts of Hill's music, confidence and killer beats.
<br>
**OVERALL: 4.5/5 STARS** 
<br>